[pytest]
# Tells pytest where to look for modules
pythonpath = .
testpaths = tests

# Forces these arguments every time you run 'pytest'
addopts = 
    --html=reports/report.html 
    --self-contained-html 
    --reruns 1 
    -v